version: '3.3'
services:
        post_db:
                image: mongo:3.2
                volumes:
                        - post_db:/data/db
                networks:
                        back_net:
                                aliases:
                                        - post_db
                                        - comment_db
        ui:
                build: ../src/ui
                image: ${USER_NAME}/ui:2.0
                ports:
                        - ${publ_port}:${publ_port}/tcp
                networks:
                        - front_net
                env_file:
                        - .env
        post:
                build: ../src/post-py
                image: ${USER_NAME}/post:1.0
                networks:
                        - front_net
                        - back_net
                env_file:
                        - .env
        comment:
                build: ../src/comment
                image: ${USER_NAME}/comment:1.0
                networks:
                        - front_net
                        - back_net
                env_file:
                        - .env
        prometheus:
                image: ${USER_NAME}/prometheus
                ports:
                        - '9090:9090'
                volumes:
                        - prometheus_data:/prometheus
                command:
                        - '--config.file=/etc/prometheus/prometheus.yml'
                        - '--storage.tsdb.path=/prometheus'
                        - '--storage.tsdb.retention=1d' # Задаем время хранения метрик в 1 день
                networks:
                        - front_net
                        - back_net
        node-exporter:
                image: prom/node-exporter:v0.15.2
                user: root
                volumes:
                        - /proc:/host/proc:ro
                        - /sys:/host/sys:ro
                        - /:/rootfs:ro
                command:
                        - '--path.procfs=/host/proc'
                        - '--path.sysfs=/host/sys'
                        - '--collector.filesystem.ignored-mount-points="^/(sys|proc|dev|host|etc)($$|/)"'
                networks:
                        - front_net
                        - back_net
volumes:
        post_db:
        prometheus_data:

networks:
        front_net:
        back_net:
