version: '3.3'
services:
        post_db:
                image: mongo:3.2
                volumes:
                        - post_db:/data/db
                networks:
                        back_net:
                                aliases:
                                        - post_db
                                        - comment_db
        ui:
                build: ./ui
                image: ${USERNAME}/ui:2.0
                ports:
                        - ${publ_port}:${publ_port}/tcp
                networks:
                        - front_net
                env_file:
                        - .env
        post:
                build: ./post-py
                image: ${USERNAME}/post:1.0
                networks:
                        - front_net
                        - back_net
                env_file:
                        - .env
        comment:
                build: ./comment
                image: ${USERNAME}/comment:1.0
                networks:
                        - front_net
                        - back_net
                env_file:
                        - .env

volumes:
        post_db:

networks:
        front_net:

        back_net:

